import { randomInt } from "./random-int";

export const randomUsername = () => mockNames[randomInt(0, mockNames.length)];

const mockNames = [
  "Alice",
  "Bob",
  "Charlie",
  "David",
  "Emma",
  "Frank",
  "Grace",
  "Henry",
  "Ivy",
  "Jack",
  "Kate",
  "Liam",
  "Mia",
  "Nora",
  "Oliver",
  "Penny",
  "Quinn",
  "Ryan",
  "Sophia",
  "Tyler",
  "Alexander",
  "Benjamin",
  "Charlotte",
  "Eleanor",
  "Frederick",
  "Isabella",
  "Jonathan",
  "Katherine",
  "Nicholas",
  "Victoria",
  "Michael James",
  "Jennifer Rose",
  "Christopher Lee",
  "Sarah Michelle",
  "Daniel Patrick",
  "Elizabeth Anne",
  "William John",
  "Margaret Mary",
  "Robert Alexander",
  "Catherine Louise",
];
